name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Cordova
      run: |
        npm install -g cordova

    - name: Create App
      run: |
        cordova create myApp com.chiots.app ChiotsApp

    - name: Copy Files
      run: |
        rm -rf myApp/www/*
        cp index.html myApp/www/
        cp -r images myApp/www/
        cp -r sounds myApp/www/

    - name: Add Android
      run: |
        cd myApp
        cordova platform add android

    - name: Build Android
      run: |
        cd myApp
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: chiots-apk
        path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
